export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_ARTICLE = 'GET_ARTICLE';
export const ARTICLE_LOADING = 'ARTICLE_LOADING';
export const ARTICLE_NOT_FOUND = 'ARTICLE_NOT_FOUND';
export const CLEAR_CURRENT_ARTICLE = 'CLEAR_CURRENT_ARTICLE';
export const GET_ARTICLES = 'GET_ARTICLES';

export const GET_CATEGORY = 'GET_CATEGORY';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND';
export const CLEAR_CURRENT_CATEGORY = 'CLEAR_CURRENT_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';

export const GET_ORG = 'GET_ORG';
export const ORG_LOADING = 'ORG_LOADING';
export const ORG_NOT_FOUND = 'ORG_NOT_FOUND';
export const CLEAR_CURRENT_ORG = 'CLEAR_CURRENT_ORG';
export const GET_ORG = 'GET_ORG';

export const GET_NOTIFY = 'GET_NOTIFY';
export const NOTIFY_LOADING = 'NOTIFY_LOADING';
export const NOTIFY_NOT_FOUND = 'NOTIFY_NOT_FOUND';
export const CLEAR_CURRENT_NOTIFY = 'CLEAR_CURRENT_NOTIFY';
export const GET_NOTIFY = 'GET_NOTIFY';